[workspace]
members = [
    "programs/*"
]
resolver = "2"

[workspace.lints.rust]
unexpected_cfgs = "allow"

[workspace.dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
